data = {
    "alabama": "Alabama is a predominantly conservative state with a strong Republican leaning. The voter demographics ...",
    "alaska": "Alaska has a unique voter demographic due to its geographical location and indigenous population. ...",
    "arizona": "Arizona is a battleground state with a growing population and changing voter demographics. ...",
    "arkansas": "Arkansas is a predominantly rural state with a conservative electorate. ...",
    "california": "California is the most populous state with a diverse electorate. ...",
    "colorado": "Colorado has a mixed electorate with a recent trend toward liberal policies. ...",
    "connecticut": "Connecticut is a small but densely populated state with a predominantly white electorate. ...",
    "delaware": "Delaware, though small in size, has a diverse electorate with a slight Democratic leaning. ...",
    "florida": "Florida is a key swing state with a diverse and complex electorate. ...",
    "georgia": "Georgia has become a battleground state with changing voter demographics. ...",
    "hawaii": "Hawaii has a unique voter demographic characterized by its significant Asian American and Pacific Islander populations. ...",
    "idaho": "Idaho is a predominantly rural state with a strong conservative leaning. ...",
    "illinois": "Illinois has a diverse electorate with significant urban and rural divides. ...",
    "indiana": "Indiana is a Midwestern state with a predominantly conservative electorate. ...",
    "iowa": "Iowa holds significant political importance due to its early caucuses in the presidential nomination process. ...",
    "kansas": "Kansas is a largely rural state with a strong conservative electorate. ...",
    "kentucky": "Kentucky has a diverse electorate with significant urban centers and rural communities. ...",
    "louisiana": "Louisiana's electorate is diverse, with African Americans making up about 33% of the population. ...",
    "maine": "Maine has a predominantly white population, accounting for about 94% of residents. ...",
    "maryland": "Maryland has a diverse population, with African Americans making up about 31%. ...",
    "massachusetts": "Massachusetts is a state with a strong liberal leaning and a highly educated electorate. ...",
    "michigan": "Michigan is a battleground state with a diverse electorate, including urban centers and rural areas. ...",
    "minnesota": "Minnesota has a politically active electorate with a tradition of high voter turnout. ...",
    "mississippi": "Mississippi is a predominantly conservative state with a significant African American population. ...",
    "missouri": "Missouri is a politically diverse state with both urban centers and rural communities. ...",
    "montana": "Montana is a large, sparsely populated state with a predominantly white population. ...",
    "nebraska": "Nebraska is a predominantly conservative state with a largely rural population. ...",
    "nevada": "Nevada has a diverse electorate with significant urban populations in Las Vegas and Reno. ...",
    "new hampshire": "New Hampshire has a small but politically significant electorate. ...",
    "new jersey": "New Jersey has a diverse and densely populated electorate. ...",
    "new mexico": "New Mexico is a southwestern state with a highly diverse electorate. ...",
    "new york": "New York is a populous and diverse state with significant political influence. ...",
    "north carolina": "North Carolina is a battleground state with a rapidly growing and changing electorate. ...",
    "north dakota": "North Dakota is a predominantly rural state with a strong conservative leaning. ...",
    "ohio": "Ohio is a key swing state with a diverse electorate. ...",
    "oklahoma": "Oklahoma is a predominantly conservative state with a significant Native American population. ...",
    "oregon": "Oregon has a diverse electorate with significant urban-rural divides. ...",
    "pennsylvania": "Pennsylvania is a key swing state with a diverse electorate. ...",
    "rhode island": "Rhode Island is the smallest state by area with a predominantly urban and suburban population. ...",
    "south carolina": "South Carolina is a southern state with a predominantly conservative electorate. ...",
    "south dakota": "South Dakota is a predominantly rural state with a strong conservative leaning. ...",
    "tennessee": "Tennessee is a southern state with a diverse electorate that leans conservative. ...",
    "texas": "Texas is a large and diverse state with significant political influence. ...",
    "utah": "Utah is a predominantly conservative state with a unique cultural landscape. ...",
    "vermont": "Vermont is a small, predominantly rural state with a strong liberal leaning. ...",
    "virginia": "Virginia has a diverse electorate with significant urban, suburban, and rural populations. ...",
    "washington": "Washington State has a diverse electorate with strong urban-rural divides. ...",
    "west virginia": "West Virginia is a predominantly rural state with a strong conservative leaning. ...",
    "wisconsin": "Wisconsin is a battleground state with a mix of urban, suburban, and rural populations. ...",
    "wyoming": "Wyoming is the least populous state with a predominantly rural and conservative electorate. ..."
}
